#!/bin/bash
#
# Set shell for job
#$ -S /bin/bash
#
# Execute job from current working directory
#$ -cwd
#
#
# merge std error and std out into one file
#$ -j y
### Don't Merge $ -j y
#

if [ -f ~/.bashrc ] ; then
    . ~/.bashrc
fi

export PATH=/opt/common/bowtie2/bowtie2-2.1.0:/home/mpirun/tools:/home/mpirun/bin:/opt/bin:$PATH
export LD_LIBRARY_PATH=/opt/lib64:/opt/lib:/ifs/data/socci/opt/lib:/home/socci/Work/SeqAna/opt/lib:$LD_LIBRARY_PATH
export SAMTOOLS_ROOT=/home/mpirun/bin/samtools

### to clear out global setting of /ifs/data/bio/Genomes/Bowtie
export BOWTIE_INDEXES=

echo "##HOST", `hostname`
echo "##CMD:>" $*
echo "##" `date`
eval $*
echo "##" `date`
